output "project" {
  description = "Project Name"
  value       = var.project
}

output "region" {
  description = "AWS Region"
  value       = var.region
}

# Network

output "network_vpc_id" {
  description = "VPC ID"
  value       = module.network.vpc_id
}

output "network_vpc_private_subnets_ids" {
  description = "IDs for the private subnets on the VPC"
  value       = module.network.vpc_private_subnets_ids
}

# EKS

output "eks_cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks_cluster.cluster_id
}

output "eks_cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = var.eks_cluster_name
}

output "eks_cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks_cluster.cluster_endpoint
}

output "eks_cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks_cluster.cluster_security_group_id
}

output "eks_kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks_cluster.kubectl_config
}

output "eks_config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks_cluster.config_map_aws_auth
}
