name: 'Run Static Application Security Testing on project'
on: push
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true # display only failed checks
          download_external_modules: true # download external terraform modules from public git repositories and terraform registry
