name: 'CI Pipeline'
on: push
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true # display only failed checks
          baseline: .github/utils/.checkov.baseline
